services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    ports:
      - "5030:5030"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_USERNAME=peracio
      - SLSKD_SLSK_PASSWORD=S@vio770621
      - SLSKD_WEB_AUTHENTICATION_USERNAME=admin
      - SLSKD_WEB_AUTHENTICATION_PASSWORD=admin123
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/savio/slskd/config:/app/config
      - /home/savio/slskd/config/slskd.yml:/app/slskd.yml
      - /home/savio/slskd/downloads:/app/downloads
      - /home/savio/slskd/incomplete:/app/incomplete
    restart: unless-stopped